# -*- coding: utf-8 -*-
"""Bienvenue dans Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st

# ===== Titre =====
st.title("Calculateur MRZ Passport")

# ===== Inputs =====
passport = st.text_input("Passport:", value="A20256311")
birth = st.text_input("Birth (YYMMDD):", value="950712")
expiry = st.text_input("Expiry (YYMMDD):", value="301125")
optional = st.text_input("Optional:", value="<<<<<<<<<<<<")

# ===== Fonctions =====
def char_to_value(c):
    if c.isdigit():
        return int(c)
    elif c.isalpha():
        return ord(c.upper()) - ord('A') + 10
    elif c == '<':
        return 0
    return 0

def calc_checksum(s):
    poids = [7,3,1]
    return sum(char_to_value(c)*poids[i%3] for i,c in enumerate(s)) % 10

# ===== Bouton =====
if st.button("Calculer Checksums"):
    # Checks individuels
    passport_check = calc_checksum(passport)
    birth_check = calc_checksum(birth)
    expiry_check = calc_checksum(expiry)
    optional_check = calc_checksum(optional)

    # Checksum global
    global_string = passport + str(passport_check) + birth + str(birth_check) + expiry + str(expiry_check) + optional + str(optional_check)
    global_check = calc_checksum(global_string)

    # ===== CSS =====
    st.markdown("""
    <style>
    /* Version détaillée */
    .detail-box {
       background: #111;
       color: #00ff9c;
       padding: 15px;
       border-radius: 18px;
       font-family: 'Courier New', monospace;
       width: fit-content;
       margin-bottom: 20px;
    }
    .detail-line {
       padding: 5px 0;
       font-size: 16px;
    }
    .label {
       font-weight: bold;
       color: #00F0FF;
    }
    .check {
       background-color: #F0F0F0;
       color: #000000;
       padding: 2px 6px;
       border-radius: 15px;
       font-weight: bold;
    }
    .detail-global {
       margin-top: 10px;
       padding-top: 5px;
       border-top: 2px solid #333;
       font-size: 18px;
       font-weight: bold;
       color: #0d6efd;
       text-align: center;
    }

    /* Version MRZ */
    @import url('https://fonts.googleapis.com/css2?family=OCR-B&display=swap');
    .mrz-box {
       background: #111;
       color: #00ff9c;
       padding: 20px;
       border-radius: 18px;
       font-family: 'OCR-B', monospace;
       font-size: 18px;
       display: flex;
       gap: 15px;
       flex-wrap: wrap;
       max-width: 500px;
       width: fit-content;
    }
    .mrz-part {
       letter-spacing: 3px;
       white-space: nowrap;
    }
    .global {
       width: 100%;
       margin-top: 10px;
       padding-top: 5px;
       border-top: 2px solid #00ff9c;
       font-size: 16px;
       font-weight: bold;
       text-align: center;
    }
    </style>
    """, unsafe_allow_html=True)

    # ===== Affichage Version Détaillée =====
    st.markdown(f"""
    <div class="detail-box">
       <div class="detail-line"><span class="label">Passport:</span> {passport} → <span class="check">{passport_check}</span></div>
       <div class="detail-line"><span class="label">Birth:</span> {birth} → <span class="check">{birth_check}</span></div>
       <div class="detail-line"><span class="label">Expiry:</span> {expiry} → <span class="check">{expiry_check}</span></div>
       <div class="detail-line"><span class="label">Optional:</span> {optional} → <span class="check">{optional_check}</span></div>
       <div class="detail-global">Checksum global MRZ: {global_check}</div>
    </div>
    """, unsafe_allow_html=True)

    # ===== Affichage Version MRZ =====
    st.markdown(f"""
    <div class="mrz-box">
       <div class="mrz-part">{passport}{passport_check}</div>
       <div class="mrz-part">{birth}{birth_check}{expiry}{expiry_check}{optional}{optional_check}</div>
       <div class="global">Checksum Global: {global_check}</div>
    </div>
    """, unsafe_allow_html=True)