# -*- coding: utf-8 -*-
"""Bienvenue dans Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import html
import re

# ===== Titre =====
st.set_page_config(page_title="Calculateur MRZ Passport", layout="centered")
st.title("Calculateur MRZ Passport")

# ===== Fonctions =====
def char_to_value(c: str) -> int:
    c = c.upper()
    if c.isdigit():
        return int(c)
    if 'A' <= c <= 'Z':
        return ord(c) - ord('A') + 10
    if c == '<':
        return 0
    return 0

def calc_checksum(s: str) -> int:
    poids = [7, 3, 1]
    total = sum(char_to_value(ch) * poids[i % 3] for i, ch in enumerate(s))
    return total % 10

def normalize_and_pad(passport, birth, expiry, optional):
    passport = passport.strip().upper().ljust(9, '<')[:9]
    optional = optional.strip().upper().ljust(14, '<')[:14]
    birth = birth.strip()
    expiry = expiry.strip()
    return passport, birth, expiry, optional

def simple_validate(passport, birth, expiry, optional):
    errors = []
    if not re.fullmatch(r'[A-Z0-9<]{1,9}', passport):
        errors.append("Passport doit contenir 1–9 caractères A‑Z, 0‑9 ou <.")
    if not re.fullmatch(r'\d{6}', birth):
        errors.append("Birth doit être au format YYMMDD (6 chiffres).")
    if not re.fullmatch(r'\d{6}', expiry):
        errors.append("Expiry doit être au format YYMMDD (6 chiffres).")
    if not re.fullmatch(r'[A-Z<]{0,14}', optional):
        errors.append("Optional doit contenir au plus 14 caractères A‑Z ou <.")
    return errors

# ===== Inputs =====
with st.form("mrz_form", clear_on_submit=False):
    col1, col2 = st.columns([1,1])
    with col1:
        passport_in = st.text_input("Passport:", value="A20256311")
        birth_in = st.text_input("Birth (YYMMDD):", value="950712")
        expiry_in = st.text_input("Expiry (YYMMDD):", value="301125")
    with col2:
        optional_in = st.text_input("Optional:", value="<<<<<<<<<<<<")
        st.markdown("**Tips**: Use `<` to pad fields")
    submit = st.form_submit_button("Calculer Checksums")

if submit:
    passport, birth, expiry, optional = normalize_and_pad(passport_in, birth_in, expiry_in, optional_in)
    errors = simple_validate(passport, birth, expiry, optional)
    if errors:
        for e in errors:
            st.error(e)
        st.stop()

    # ===== Calcul des checks =====
    passport_check = calc_checksum(passport)
    birth_check = calc_checksum(birth)
    expiry_check = calc_checksum(expiry)
    optional_check = calc_checksum(optional)

    # Construction chaîne globale MRZ standardisée
    nationality = "USA"
    sex = "M"
    part_passport = passport + str(passport_check)
    part_dates = birth + str(birth_check) + sex + expiry + str(expiry_check)
    part_optional = optional + str(optional_check)
    global_string = part_passport + nationality + part_dates + part_optional
    global_check = calc_checksum(global_string)

    # ===== CSS + animations (Copilot style) =====
    st.markdown("""
    <style>
    .app-container { display:flex; gap:20px; flex-wrap:wrap; justify-content:center; align-items:flex-start; }
    .card { background: linear-gradient(135deg, rgba(10,12,20,0.95), rgba(18,22,30,0.95)); border-radius:14px; padding:18px; box-shadow:0 8px 30px rgba(2,6,23,0.6); color:#dfffe6; width:520px; font-family: Inter, ui-sans-serif, system-ui; transition: transform 300ms; border:1px solid rgba(255,255,255,0.03); }
    .card:hover { transform:translateY(-6px); box-shadow:0 18px 50px rgba(2,6,23,0.75); }
    .card h3 { margin:0 0 8px 0; color:#9fffa8; font-weight:700; letter-spacing:0.6px; }
    .mrz { background: linear-gradient(90deg, rgba(2,8,20,0.95), rgba(6,12,30,0.95)); border-radius:10px; padding:12px 14px; font-family:'OCR-B', monospace; color:#00ff9c; letter-spacing:3px; font-size:18px; display:flex; flex-direction:column; gap:8px; }
    .badge { display:inline-block; background:linear-gradient(90deg,#ffffff,#f0f0f0); color:#000; padding:6px 10px; border-radius:999px; font-weight:700; animation: pop 900ms ease; }
    @keyframes pop { 0% { transform:scale(.6); opacity:0; } 60% { transform:scale(1.08); opacity:1; } 100% { transform:scale(1); } }
    .detail-row { display:flex; justify-content:space-between; gap:12px; align-items:center; padding:6px 0; border-bottom:1px dashed rgba(255,255,255,0.03); }
    .label { color:#7be3ff; font-weight:600; }
    .muted { color:#9fd8ff; font-size:13px; }
    .global-check { margin-top:10px; padding-top:10px; border-top:2px solid rgba(0,255,156,0.08); text-align:center; font-weight:800; color:#00ffd1; font-size:20px; position:relative; }
    .global-check::after { content:""; position:absolute; left:50%; transform:translateX(-50%); bottom:-8px; width:60px; height:4px; background:linear-gradient(90deg,#00ffd1,#7be3ff); border-radius:4px; animation: slide 1.6s infinite linear; opacity:0.9; }
    @keyframes slide { 0% { transform:translateX(-50%) translateX(-30px); opacity:0.6; } 50% { transform:translateX(-50%) translateX(30px); opacity:1; } 100% { transform:translateX(-50%) translateX(-30px); opacity:0.6; } }
    .copy-btn { background: linear-gradient(90deg,#00ffd1,#7be3ff); color:#002; border:none; padding:8px 12px; border-radius:10px; font-weight:700; cursor:pointer; box-shadow:0 8px 20px rgba(0,255,209,0.08); }
    .copy-btn:active { transform: translateY(1px); }
    </style>
    """, unsafe_allow_html=True)

    # ===== Safe HTML content =====
    safe_passport = html.escape(passport)
    safe_birth = html.escape(birth)
    safe_expiry = html.escape(expiry)
    safe_optional = html.escape(optional)
    safe_part_passport = html.escape(part_passport)
    safe_part_dates = html.escape(part_dates)
    safe_part_optional = html.escape(part_optional)
    safe_final_mrz = html.escape(global_string + str(global_check))

    st.markdown(f"""
    <div class="app-container">
      <div class="card">
        <h3>Résultats détaillés</h3>
        <div class="detail-row"><div><span class="label">Passport</span><div class="muted">{safe_passport}</div></div><div class="badge">{passport_check}</div></div>
        <div class="detail-row"><div><span class="label">Birth</span><div class="muted">{safe_birth}</div></div><div class="badge">{birth_check}</div></div>
        <div class="detail-row"><div><span class="label">Expiry</span><div class="muted">{safe_expiry}</div></div><div class="badge">{expiry_check}</div></div>
        <div class="detail-row"><div><span class="label">Optional</span><div class="muted">{safe_optional}</div></div><div class="badge">{optional_check}</div></div>
        <div class="global-check">Checksum global MRZ : {global_check}</div>
      </div>

      <div class="card">
        <h3>Aperçu MRZ</h3>
        <div class="mrz">
          <div>{safe_part_passport} | {nationality} | {safe_part_dates}</div>
          <div style="opacity:0.7; font-size:13px;">Optional + check : {safe_part_optional}</div>
        </div>
        <div style="margin-top:12px; display:flex; gap:8px; align-items:center;">
          <button class="copy-btn" onclick="navigator.clipboard.writeText('{safe_final_mrz}')">Copier MRZ</button>
          <div style="font-family:monospace; color:#bfffdc; padding:6px 8px; border-radius:8px; background:rgba(0,0,0,0.25);">Global: <strong>{global_check}</strong></div>
        </div>
        <pre style="background:rgba(0,0,0,0.35); padding:10px; border-radius:8px; color:#00ff9c; font-family:'OCR-B', monospace;">{safe_final_mrz}</pre>
      </div>
    </div>
    """, unsafe_allow_html=True)