# -*- coding: utf-8 -*-
"""Bienvenue dans Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import pandas as pd
import re
import html

# ===== Titre =====
st.set_page_config(page_title="Calculateur MRZ Passport", layout="centered")
st.title("Calculateur MRZ Passport")

# ===== Fonctions utilitaires =====
def char_to_value(c: str) -> int:
    c = c.upper()
    if c.isdigit():
        return int(c)
    if 'A' <= c <= 'Z':
        return ord(c) - ord('A') + 10
    if c == '<':
        return 0
    return 0

def calc_checksum(s: str) -> int:
    poids = [7, 3, 1]
    total = 0
    for i, ch in enumerate(s):
        total += char_to_value(ch) * poids[i % 3]
    return total % 10

def validate_and_normalize(passport, birth, expiry, optional, nationality, sex):
    errors = []
    passport = passport.strip().upper()
    birth = birth.strip()
    expiry = expiry.strip()
    optional = optional.strip().upper()
    nationality = nationality.strip().upper()
    sex = sex.strip().upper() if sex else '<'

    # Basic patterns
    if not re.fullmatch(r'[A-Z0-9<]{1,9}', passport):
        errors.append("Passport doit contenir 1–9 caractères A‑Z, 0‑9 ou <.")
    if not re.fullmatch(r'\d{6}', birth):
        errors.append("Birth doit être au format YYMMDD (6 chiffres).")
    if not re.fullmatch(r'\d{6}', expiry):
        errors.append("Expiry doit être au format YYMMDD (6 chiffres).")
    if not re.fullmatch(r'[A-Z<]{0,14}', optional):
        errors.append("Optional doit contenir au plus 14 caractères A‑Z ou <.")
    if not re.fullmatch(r'[A-Z]{2,3}|[A-Z<]{1,3}', nationality):
        errors.append("Nationality doit être 3 lettres ISO (ex: USA).")
    if sex not in ('M', 'F', '<'):
        errors.append("Sex doit être M, F ou laissé vide (sera remplacé par <).")

    # Padding to MRZ lengths
    passport = passport.ljust(9, '<')
    optional = optional.ljust(14, '<')
    nationality = nationality.ljust(3, '<')
    sex = sex if sex in ('M','F') else '<'

    return passport, birth, expiry, optional, nationality, sex, errors

# ===== Inputs =====
with st.form("mrz_form"):
    col1, col2 = st.columns(2)
    with col1:
        passport_in = st.text_input("Passport", value="A20256311")
        birth_in = st.text_input("Birth (YYMMDD)", value="950712")
        expiry_in = st.text_input("Expiry (YYMMDD)", value="301125")
    with col2:
        optional_in = st.text_input("Optional (14 chars)", value="<<<<<<<<<<<<")
        nationality_in = st.text_input("Nationality (3 letters)", value="USA")
        sex_in = st.text_input("Sex (M/F)", value="M")
    submit = st.form_submit_button("Calculer Checksums")

if submit:
    passport, birth, expiry, optional, nationality, sex, errors = validate_and_normalize(
        passport_in, birth_in, expiry_in, optional_in, nationality_in, sex_in
    )

    if errors:
        for e in errors:
            st.error(e)
        st.stop()

    # ===== Calculs individuels =====
    passport_check = calc_checksum(passport)
    birth_check = calc_checksum(birth)
    expiry_check = calc_checksum(expiry)
    optional_check = calc_checksum(optional)

    # ===== Construction de la chaîne globale (43 caractères avant le check global) =====
    # Format MRZ ligne 2 : passport(9) + passport_check(1) + nationality(3) + birth(6) + birth_check(1)
    # + sex(1) + expiry(6) + expiry_check(1) + optional(14) + optional_check(1) = 43 chars
    part_passport = passport + str(passport_check)
    part_dates = birth + str(birth_check) + sex + expiry + str(expiry_check)
    part_optional = optional + str(optional_check)
    global_string = part_passport + nationality + part_dates + part_optional

    # Safety check length
    if len(global_string) != 43:
        st.error(f"Erreur interne: la chaîne globale doit faire 43 caractères mais fait {len(global_string)}.")
        st.stop()

    global_check = calc_checksum(global_string)

    # ===== Tableau détaillé caractère par caractère =====
    rows = []
    cumulative = 0
    poids = [7, 3, 1]
    for i, ch in enumerate(global_string):
        val = char_to_value(ch)
        w = poids[i % 3]
        prod = val * w
        cumulative += prod
        rows.append({
            "Position": i + 1,
            "Caractère": ch,
            "Valeur": val,
            "Poids": w,
            "Produit": prod,
            "Somme cumulée": cumulative
        })
    df = pd.DataFrame(rows)

    # ===== CSS pour affichage MRZ et détails =====
    st.markdown("""
    <style>
    .detail-box { background:#0b1220; color:#dfffe6; padding:14px; border-radius:12px; font-family:monospace; }
    .label { color:#7be3ff; font-weight:700; }
    .check { background:#ffffff; color:#000; padding:3px 8px; border-radius:10px; font-weight:700; }
    .mrz-box { background:#0b1220; color:#bfffdc; padding:16px; border-radius:12px; font-family: 'OCR-B', monospace; font-size:18px; }
    .mrz-line { letter-spacing:3px; white-space:nowrap; }
    .small { font-size:14px; color:#9fd8ff; }
    </style>
    """, unsafe_allow_html=True)

    # ===== Affichage Version Détaillée =====
    st.markdown("<div class='detail-box'>", unsafe_allow_html=True)
    st.markdown(f"<div class='small'><span class='label'>Passport</span> : {html.escape(passport)} → <span class='check'>{passport_check}</span></div>", unsafe_allow_html=True)
    st.markdown(f"<div class='small'><span class='label'>Birth</span> : {html.escape(birth)} → <span class='check'>{birth_check}</span></div>", unsafe_allow_html=True)
    st.markdown(f"<div class='small'><span class='label'>Expiry</span> : {html.escape(expiry)} → <span class='check'>{expiry_check}</span></div>", unsafe_allow_html=True)
    st.markdown(f"<div class='small'><span class='label'>Optional</span> : {html.escape(optional)} → <span class='check'>{optional_check}</span></div>", unsafe_allow_html=True)
    st.markdown(f"<div style='margin-top:8px; font-weight:700; color:#9fffa8'>Checksum global MRZ : {global_check}</div>", unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

    # ===== Affichage MRZ prêt à copier =====
    mrz_line1 = html.escape(part_passport + nationality + part_dates[:0])  # not used, keep for clarity
    mrz_line2 = html.escape(part_passport + nationality + part_dates + part_optional)
    st.markdown("<div class='mrz-box'>", unsafe_allow_html=True)
    st.markdown(f"<div class='mrz-line'>{html.escape(part_passport)} {html.escape(nationality)} {html.escape(birth + str(birth_check) + sex + expiry + str(expiry_check))}</div>", unsafe_allow_html=True)
    st.markdown(f"<div style='margin-top:8px; font-weight:700; color:#bfffdc'>MRZ ligne 2 complète</div>", unsafe_allow_html=True)
    st.code(part_passport + nationality + part_dates + part_optional, language=None)
    st.markdown("</div>", unsafe_allow_html=True)

    # ===== Tableau détaillé affiché =====
    st.markdown("### Détail pas à pas caractère par caractère")
    st.dataframe(df, use_container_width=True)

    # ===== Somme et modulo affichés clairement =====
    total_sum = df["Produit"].sum()
    st.markdown(f"**Somme totale des produits** : {total_sum}")
    st.markdown(f"**Modulo 10** : {total_sum} mod 10 = **{global_check}**")

    # ===== Zone pour copier facilement la ligne MRZ finale =====
    st.markdown("### Ligne MRZ finale (à copier)")
    final_mrz = part_passport + nationality + part_dates + part_optional + str(global_check)
    st.code(final_mrz, language=None)